### ISSUE TITLE
Repeated null pointer crash in background v0.7.29

### ISSUE THREAD

**Issue by casual-will** [ente-io/photos-app#936]
```
type: crash
osVersion: google/sunfish/sunfish:13/TQ2A.230305.008.C1/2023031500:user/release-keys
package: io.ente.photos.independent:429
process: io.ente.photos.independent
processUptime: 406 + 702 ms

java.lang.NullPointerException
	at n8.b.c(MediaExtensionPlugin.kt:1)
	at n8.b.f(MediaExtensionPlugin.kt:1)
	at n8.b.a(Unknown Source:0)
	at n8.a.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```

**Comment by vishnukvmd** [comment]
Hey! Thank you for reporting, this issue has already been fixed on `main`. Could you please grab the latest build from https://github.com/ente-io/photos-app/releases/latest?
